### ISSUE TITLE
Did you release it to Google Play yet?

### ISSUE THREAD

**Issue by tribals** [obynio/elmyra#1]
Hi! Nice working! Did you release it yet?

**Comment by obynio** [comment]
Hey, I just noticed I missed this issue, sorry. I wasn't expecting anyone to take interest in this PoC...

Nope, not released yet because I think the method I used might go against the Google Play Terms of Service. Maybe I'm wrong though... I'm not using my Pixel 4 anymore but I'll try to release it when I get some free time.

**Comment by tribals** [comment]
Thank you for update! :grin:
